site_name: Dicaeopolis' Wiki

theme:
  name: material
  custom_dir: docs/overrides
  custom_dir: overrides
  favicon: favicon.png
  logo: favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.titles
    - navigation.tabs
    - navigation.indexes
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  language: zh

hooks:
  - docs/overrides/hooks/reading_time.py    # é˜…è¯»æ—¶é—´ç»Ÿè®¡

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  
      generic: true
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
      # baselevel: 2
      # toc_depth: 3  # æ§åˆ¶æ ‡é¢˜å±‚çº§æ·±åº¦
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      linenums: true # æ˜¾ç¤ºè¡Œå·
      # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mermaid2
  - encryptcontent:
      title_prefix: '[Protected]'
      summary: 'ä¸ç»™ä½ çœ‹ğŸ˜'
      placeholder: 'å£ä»¤è¾“å¯¹äº†æ‰èƒ½çœ‹å“¦'
      decryption_failure_message: 'è¾“é”™äº†å“¦~'
      encryption_info_message: 'ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡'

extra_css:
  - themes/css/custom.css
  - themes/css/simpleLightbox.min.css
  - themes/css/pied_piper.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - stylesheets/customize.css  #æŒ‰é’®åœ†è§’åŒ–
  - assets/css/custom.css
 
extra_javascript:
  - assets/js/custom.js
  - themes/js/custom.js
  - themes/js/simpleLightbox.min.js
  - themes/js/optionalConfig.js
  - themes/js/mermaidloader.js
  - themes/js/umlconvert.js
  - themes/js/mathjax.js
  - themes/js/katex.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js
  - https://cdn.jsdelivr.net/npm/@mermaid-js/mermaid-mindmap@9.3.0/dist/diagram-definition.0faef4c2.min.js
  - https://cdn.jsdelivr.net/npm/markdown-it-plantuml@1.4.1/index.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  

nav:
  - æ·±åº¦ç¥ç»ç½‘ç»œ:
    - 'DNN/index.md'
    - å¤ç°è®°å½•:
      - 'DNN/model-expr/index.md'
      - å›¾åƒåˆ†ç±»ç›¸å…³æ¨¡å‹å¤ç°æ‰‹è®°: 'DNN/model-expr/Image-models-replication.md'
      - DC-GAN è€å©†ç”Ÿæˆå™¨: 'DNN/model-expr/DC-GAN-è€å©†ç”Ÿæˆå™¨.md'
      - å›¾åƒè¯­ä¹‰åˆ†å‰²å’Œç›®æ ‡æ£€æµ‹ç›¸å…³æ¨¡å‹å¤ç°æ‰‹è®°: 'DNN/model-expr/S-and-D-models-replication.md'
    - ä¼˜åŒ–å™¨:
      - 'DNN/optimizer/index.md'
      - åç»­çš„å†™ä½œè®¡åˆ’: 'DNN/optimizer/misc.md'
      - ç¬¦å·æ¢¯åº¦ä¸‹é™: 'DNN/optimizer/SignGD.md'
      - è‡ªé€‚åº”å­¦ä¹ ç‡æ”¹è¿›ç­–ç•¥: 'DNN/optimizer/Adaptive.md'
      - SGD ç³»åˆ—ç®—æ³•: 'DNN/optimizer/SGD.md'
  - é…ç½®å’Œæ‚è°ˆç¬”è®°:
    - 'misc/index.md'
    - åŠŸèƒ½æµ‹è¯•é¡µé¢: 'misc/test.md'
  - ä¼ ç»Ÿç®—æ³•ä¸æ€§èƒ½:
    - 'algorithm/index.md'
    - STLçš„ä¸€äº›æ€§èƒ½æµ‹è¯•: 'algorithm/benchmark-on-stl.md'
    - å—¯é€ è½®å­: 'algorithm/stl-wheels.md'
    - æ•´æ•°ç¯å–æ¨¡æ¨¡æ¿: 'algorithm/template-on-numeric-ring.md'
  - æ ¡å†…è¯¾ç¨‹çŸ¥è¯†:
    - 'campus-sources/index.md'
    - ã€Šæ•°æ®ç»“æ„ã€‹åˆ’é‡ç‚¹ç¬”è®°: 'campus-sources/ds-keynote.md'
    - ã€Šæ•°æ®ç»“æ„ã€‹æœŸæœ«å¤ä¹ é¢˜é¢˜è§£: 'campus-sources/ds-write-up.md'
    - è‡ªåŠ¨ç­¾åˆ°è„šæœ¬: 'campus-sources/autosignin.md'